import NotificationProvider from '@/providers/NotificationProvider'
import type { Metadata } from 'next'
import { Rubik } from 'next/font/google'
import './globals.css'

const inter = Rubik({ weight: ['400', '700'], subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NotificationProvider>{children}</NotificationProvider>
      </body>
    </html>
  )
}
