name: ci-aproveme-workflow
on: 
    push:
        branches:
            - main

env:
    NODE_ENV: ${{ secrets.NODE_ENV }}
    JWT_SECRET: ${{ secrets.JWT_SECRET }}
    DATABASE_URL: ${{ secrets.DATABASE_URL }}
    REDIS_URL: ${{ secrets.REDIS_URL }}
    REDIS_HOST: ${{ secrets.REDIS_HOST }}
    REDIS_PORT: ${{ secrets.REDIS_PORT }}
    EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
    EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
    EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
    EMAIL_HOST: ${{ secrets.EMAIL_HOST }}


jobs:
    check-application:
        strategy:
            matrix:
                node-version: [19.x]
        runs-on: ubuntu-latest
        
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                node-version: ${{ matrix.node-version }}
            - run: npm install
            - run: npm run test-unit

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to DockerHub
              uses: docker/login-action@v1 
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push
              id: docker_build
              uses: docker/build-push-action@v2
              with:
                context: .
                file: ./back-end/Dockerfile
                push: true
                tags: pedronx/aproveme-back:latest

    deploy-application:
        needs: check-application
        runs-on: self-hosted
        steps:
            - name: Docker Compose
              run: docker-compose -f docker-compose.yml up -d
