name: ci-aproveme-workflow
on: 
    push:
        branches:
            - main

jobs:
    check-application:
        strategy:
            matrix:
                node-version: [19.x]
        runs-on: ubuntu-latest
        
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                node-version: ${{ matrix.node-version }}


            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to DockerHub
              uses: docker/login-action@v1 
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push
              id: docker_build
              uses: docker/build-push-action@v2
              with:
                context: .
                file: ./back-end/Dockerfile
                push: true
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/aproveme-back:latest

    deploy-application:
        needs: check-application
        runs-on: self-hosted
        steps:
            - name: Stop and remove container
              run: docker stop aproveme-back && docker rm aproveme-back || true

            - name: Pull image
              run: sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/aproveme-back:latest

            - name: Run redis container
              run: sudo docker run -d -p 6379:6379 --name redis redis \ 
                -v ./back-end/data/redis:/data/redis

            - name: Run rabbitmq container
              run: sudo docker run -d -p 25672:25672 -p 15672:15672 -p 5672:5672 --name rabbitmq rabbitmq:3.6.6-management 

            - name: Run container
              run: sudo docker run -d -p 3333:3333 --name aproveme-back ${{ secrets.DOCKERHUB_USERNAME }}/aproveme-back:latest \ 
                --restart=always \ 
                -e JWT_SECRET=secret \
                -e DATABASE_URL=file:./dev.db \
                -e REDIS_URL=redis://redis:6379 \
                -e REDIS_HOST=redis \
                -e REDIS_PORT=6379 \
                -e EMAIL_USERNAME=7c120fba39e28b \
                -e EMAIL_PASSWORD=80ac73b879dcf6 \
                -e EMAIL_PORT=2525 \
                -e EMAIL_HOST=sandbox.smtp.mailtrap.io \
                -v ./back-end:/app

              
